name: Frontend Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository (코드 체크아웃)
        uses: actions/checkout@v4

      - name: Set up Node 23 (Node 설정)
        uses: actions/setup-node@v4
        with:
          node-version: 23.7.0

      - name: Install Dependencies And Run Tests (Vue 빌드 및 테스트)
        run: |
          npm install
          npm run build

  notify-jenkins:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Jenkins에 배포 요청
        run: |
          CRUMB=$(curl -u "blws:${{ secrets.JENKINS_API_TOKEN }}" -s "${{ secrets.JENKINS_CRUMB_URL }}" | jq -r '.crumb')
          curl -X POST -u "blws:${{ secrets.JENKINS_API_TOKEN }}" -H "Jenkins-Crumb:$CRUMB" "${{ secrets.JENKINS_WEBHOOK_URL }}"